### ISSUE TITLE
Default command output format changes

### ISSUE THREAD

**Issue by brianbunke** [lipkau/Spread#2]
### Expected Behavior
All commands within the script block observe their normal default output behaviors

### Current Behavior
Only the first command in a script block outputs as expected. Each subsequent new command seems to add something like a `| Format-List *` at the end.

### Possible Solution
No idea if this is within your power or not!

### Steps to Reproduce (for bugs)
```posh
Invoke-WithParameter -ScriptBlock {
    # Outputs normally
    Get-Service
    # Outputs in list format, like it forgot ".format.ps1xml" files exist
    Get-Process
} Name '*y*'

```

### Your Environment
Spread 1.1.0.0
PowerShell 5.1

**Comment by Jaykul** [comment]
You can't output different types of objects in one pipeline to the console formatter. You would need `| Out-Default` on each output ...
